name: Django CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"
            - name: Go to working directory
              run: |
                    cd backend
                    pwd
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pwd
                  pip install -r requirements.txt